instance_type = "t3.micro"
app_port = "3000"
project_name = "test"
github_repo = "yashchokhat/test"
create_oidc_provider = "false"
oidc_provider_arn = "arn:aws:iam::751667630303:oidc-provider/token.actions.githubusercontent.com"
aws_region = "ap-south-1"
