oidc_provider_arn = "arn:aws:iam::751667630303:oidc-provider/token.actions.githubusercontent.com"
instance_type = "t3.micro"
app_port = "3000"
aws_region = "ap-south-1"
project_name = "test"
github_owner = "yashchokhat"
github_repository = "vertex-on-edge-cli"
create_oidc_provider = "false"
